### ISSUE TITLE
Not resolved iTextSharp.text.pdf.parser reference 

### ISSUE THREAD

**Issue by prasadpawale** [VahidN/iTextSharp.LGPLv2.Core#10]
I am using .NET Core framework and used iTextSharp.LGPLv2.Core 1.2.6 package for PDF operations.
I want to use PdfTextExtractor for some text replacement, but says namespace not found.

**Comment by VahidN** [comment]
It's duplicate of https://github.com/VahidN/iTextSharp.LGPLv2.Core/issues/7 and https://github.com/VahidN/iTextSharp.LGPLv2.Core/issues/3
