### ISSUE TITLE
Unknown encryption type R = 6 error

### ISSUE THREAD

**Issue by iamSathishMohan** [VahidN/iTextSharp.LGPLv2.Core#100]
# Summary of the issue
While reading the PDF2.0 version of pdf document using the PdfReader throws an error like **Unknown encryption type R = 6**

## Environment

```
iTextSharp.LGPLv2.Core version: 1.7.3
.NET Core SDK version: 3.1 & 5.0
IDE: Visual Studion Community 2019
```

## Example code/Steps to reproduce:

```
var reader = new PdfReader('c:\samples\sample.pdf')
```

## Output:
iTextSharp.text.exceptions.InvalidPdfException: 'Unknown encryption type R = 6'
```
Exception message:
Full Stack trace:
```

**Comment by slavat** [comment]
A related issue https://github.com/LibrePDF/OpenPDF/issues/375
