### ISSUE TITLE
It's about how to set 'BaseFont.NOT_EMBEDDED '

### ISSUE THREAD

**Issue by LucasDang** [VahidN/iTextSharp.LGPLv2.Core#11]
I created a font with <BaseFont baseFont = BaseFont.CreateFont(@"c:\windows\fonts\SIMHEI.TTF", BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED)>,

but the font still embed in pdf,so i print with <baseFont.IsEmbedded()> and the result is true,so i want to konw why?

I want to get your help，thanks a lot .

**Comment by VahidN** [comment]
[This how Unicode fonts and Unicode characters rendering works](https://stackoverflow.com/a/4567390/298573).

**Comment by LucasDang** [comment]
Still that problem, the embedded font make pdf too large that i can't use ! 

I use 
```
         BaseFont.AddToResourceSearch("iTextAsian.dll");
         BaseFont.AddToResourceSearch("iTextAsianCmaps.dll");
         BaseFont baseFont = BaseFont.CreateFont("STSong-Light", "UniGB-UCS2-H",  
         BaseFont.NOT_EMBEDDED);
```
but got errer message "STSong-Light' with 'UniGB-UCS2-H' is not recognized” . I put two 'dll' file in 
'bin/Debug/'  and add references .
 Also, i saw the your answer at stackoverflow, i try to add 
```
         stamp.AcroFields.AddSubstitutionFont(baseFont);
```
but still not work!

The  two 'dll' file is the oldest version .

I'm not good at English,thanks anyway!

**Comment by VahidN** [comment]
You can't do anything about that. Unicode fonts must be embedded. This how it works and designed.
