### ISSUE TITLE
`System.Drawing.Common` no longer supported for non-Windows

### ISSUE THREAD

**Issue by conficient** [VahidN/iTextSharp.LGPLv2.Core#110]
# Summary 

Microsoft is withdrawing support for using `System.Drawing.Common` on non-Windows systems:
https://docs.microsoft.com/en-gb/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

There is a workaround for now but we can expect this to stop working completely at some point. They suggest one of three alternatives:

> To use these APIs for cross-platform apps, migrate to one of the following libraries:
>
> - [ImageSharp](https://github.com/SixLabors/ImageSharp)
>  - [SkiaSharp](https://github.com/mono/SkiaSharp)
>  - [Microsoft.Maui.Graphics](https://github.com/dotnet/Microsoft.Maui.Graphics)

## Environment
```
iTextSharp.LGPLv2.Core version: 1.8.0
.NET Core SDK version: 6.x
IDE: n/a
```

**Comment by vsolominov** [comment]
Hello, @VahidN!

I propose a patch that replaces the `System.Drawing.Common` library with the [IronSoftware.System.Drawing](https://github.com/iron-software/IronSoftware.System.Drawing) and [SkiaSharp](https://github.com/mono/SkiaSharp) libraries. Perhaps you implement a better solution, but for inspiration, I suggest you check out the solution.

[iTextSharp.LGPLv2.Core-System.Drawing.Common-remove.patch](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/10243638/iTextSharp.LGPLv2.Core-System.Drawing.Common-remove.patch)
