### ISSUE TITLE
Strong naming the library

### ISSUE THREAD

**Issue by petarpetrovt** [VahidN/iTextSharp.LGPLv2.Core#117]
Unsigned assemblies can cause a lot of issues for projects that require signed assemblies. Although there are alternatives such as signing the assembly yourself via `StrongNamer`, they don't always work correctly for every situation and can cause a lot of problems when the project's dependencies become more complex. Additionally, some of the articles mentioned in #29 have changed their stance on strong-naming assemblies. Here's a link for reference: [link](https://www.pedrolamas.com/2018/09/11/start-strong-naming-your-assemblies/).

According to the dotnet team's citation - [link](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md)
> Because of the viral nature of strong-naming, it is recommended that publicly published .NET libraries are strong-named. Not strong-naming a .NET library excludes anyone who does need to strong-name their application or library from using it. Read more about .NET libraries and strong-naming in the [.NET Library Guidance](https://docs.microsoft.com/dotnet/standard/library-guidance/strong-naming).

In light of these considerations, it may be worthwhile to reconsider the benefits of using strong-naming.

**Comment by VahidN** [comment]
The first step is to say why I'm not going to do that (and it's done), the next step is: If this library is not suitable for you, don't use it. Don't like it? Don't use it.
