### ISSUE TITLE
Add Font Location for Windows

### ISSUE THREAD

**Issue by mayurjansari** [VahidN/iTextSharp.LGPLv2.Core#123]
In Windows OS some Fonts are in

**"%LOCALAPPDATA%\Microsoft\Windows\Fonts"**

So, Add this location to Library.

**Comment by VahidN** [comment]
[This is how you should define and use a font.](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/TestUtils.cs#L70)
