### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by slubowsky** [VahidN/iTextSharp.LGPLv2.Core#124]
# Summary of the issue
Calling PdfCopy.GetImportedPage never returns in some cases. Its caught in endless loop. (This worked for me until recently, updating to new version of library breaks it)

It appears that the issue is caused by code added in this commit - https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/1d723a006bc152ec4a55321105edd526358cc13b#diff-2008b4fd865a466332b1b14819904d18188fae02b0cecd597a409fa67071ee57
 
Line 48
`if (srcObj.IsStream() || srcObj.IsDictionary())`
`|| srcObj.IsDictionary()` was added. This is causing the endless loop.  Removing it allows the code to complete and my PDF is successfully generated.

**Comment by VahidN** [comment]
Can you post a .pdf file sample which causes this issue?

**Comment by slubowsky** [comment]
[UB04_form.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/11637739/UB04_form.pdf)
