### ISSUE TITLE
iTextSharp.text.html.simpleparser.HTMLWorker does not exist

### ISSUE THREAD

**Issue by appndigital** [VahidN/iTextSharp.LGPLv2.Core#13]
Hello,

thanks for your work.
We are trying to use the HTMLWorker but we get a "doest not exist" error at build.
We are using 1.3.2 version (<PackageReference Include="iTextSharp.LGPLv2.Core" Version="1.3.2" />) and working with Visual Code.

Do you know where the error might come ?

Many thanks

**Comment by VahidN** [comment]
It's renamed to [HtmlWorker](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/HtmlWorkerTests.cs#L42).

**Comment by appndigital** [comment]
Many thanks !
