### ISSUE TITLE
Adding a scaled an image to a document produces PDF with the same size as not-scaled image. 

### ISSUE THREAD

**Issue by aleksei-oecd** [VahidN/iTextSharp.LGPLv2.Core#135]
Not sure if this is intended behavior. I'm adding a large image and before adding it to a document I do resize (scale) it to a smaller size

```
var image = Image.GetInstance("large.jpg");
image.ScaleAbsolute(50,60);
image.SetAbsolutePosition(100,100);
doc.Add(image);
```

The image in the resulting pdf document is correctly sized, but it seems original image is embedded into PDF as the size of a document (in MB) is very close to the size of an image (MB). Probably this is how it is supposed to work, but what is then a proper way to add resized only image to a document ?

**Comment by VahidN** [comment]
Yes, Scaling an image, doesn't change its actual size.
