### ISSUE TITLE
PdfTextExtractor

### ISSUE THREAD

**Issue by SuperJMN** [VahidN/iTextSharp.LGPLv2.Core#14]
Hello! I'm currently using itextsharp 5.+ on my application, but I would like to port it to work in ASP.NET Core 2.0. The functionality I'm using right now is provided by `PdfTextExtractor` and related classes.

By now, the only migration project I've found is this, but it's 4.x. Do you have plans to upgrade it?

Thanks!

**Comment by VahidN** [comment]
No. v5.x is not LPGL anymore.
