### ISSUE TITLE
Error when extracting images from some tif files

### ISSUE THREAD

**Issue by maksneboronov** [VahidN/iTextSharp.LGPLv2.Core#142]
# Summary of the issue

It is necessary to extract the images from the `tif` file and save each page in the file system in `pdf` format. The code below does not work correctly for the file [test.tif](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/14743503/test.pdf) (the file extension must be changed after downloading, because the `tif` file cannot be attached to the task). The result is given in the file [result.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/14743489/result.pdf), this file cannot be read, for example, by Adobe Acrobat Reader.

I also tested the `Verify_TIFF_extra_samples_CanBeAddedToPdfDocument` method with this file and got a similar error.

## Environment

```
iTextSharp.LGPLv2.Core version: 3.4.18
net7.0
```

## Example code:

```c#
public static void SomeMethod(string inputFilePath)
{
    var randomAccessFile = new RandomAccessFileOrArray(inputFilePath);
    var numberOfPages = TiffImage.GetNumberOfPages(randomAccessFile);

    for (var i = 1; i <= numberOfPages; i++)
    {
        var image = TiffImage.GetTiffImage(randomAccessFile, i);
        image.ScaleAbsolute(image.Width, image.Height);
        image.SetAbsolutePosition(absoluteX: 0, absoluteY: 0);
        image.SetDpi(image.DpiX, image.DpiY);

        using (var stream = File.OpenWrite($"{i}.pdf"))
        {
            using (var document = new Document(image, 0, 0, 0, 0))
            {
                var writer = PdfWriter.GetInstance(document, stream);
                writer.CompressionLevel = PdfStream.NO_COMPRESSION;

                document.Open();
                document.Add(image);
            }
        }
    }
}
```

**Comment by VahidN** [comment]
Is this a tiff reader library? No!
[I added a new sample](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/TiffImageTests.cs#L102) about this subject using [libtiff.net](https://github.com/BitMiracle/libtiff.net) library and Skiasharp which is part of iTextSharp now.
