### ISSUE TITLE
Updating from 1.7.5 seems to have broken reading converted PDFs from LibreOffice

### ISSUE THREAD

**Issue by 36PopTarts** [VahidN/iTextSharp.LGPLv2.Core#146]
# Summary of the issue
I have a .NET Core 2.2 service application that manipulates documents. It converts every document type into PDF. For some document types (.doc, etc), it uses LibreOffice to convert to PDF. Afterward it uses iTextSharp to read the document lazily, using RandomAccessFileOrArray. This works well and seems quite performant. Recently, I've had to update this service to .NET 6 because of other inter-dependencies with other services, and in doing so I also updated the dependent libraries, which included iTextSharp LGPL Core. After that, it is unable to open the converted documents from LibreOffice. It throws an exception claiming the PDF does not have a catalog. The PDF document contents are exactly the same as before.

## Environment

```
iTextSharp.LGPLv2.Core version: 1.7.5 (working), 3.4.19 (broken)
.NET Core SDK version: 2.2 (working), 6 (broken)
IDE: Visual Studio 2022 64-bit
```

## Example code/Steps to reproduce:

Convert .doc to PDF using LibreOffice. Command line in Unix-based OS:
```
soffice \
        -env:SingleAppInstance="false" \
        -env:UserInstallation="file:///some/temp/directory" \
        --headless --norestore --convert-to pdf \
        "/some/path/to/converted/document.doc"
```

.NET code causing the exception:
```
var documentPath = "/some/path/to/converted/document.pdf";
var pdfReader = new PdfReader(new RandomAccessFileOrArray(documentPath), null);
```

## Output:

```
Message: This invalid PDF file doesn't have a catalog.
Type: iTextSharp.text.exceptions.InvalidPdfException
StackTrace:    at iTextSharp.text.pdf.PdfReader.ReadPages() in D:\a\iTextSharp.LGPLv2.Core\iTextSharp.LGPLv2.Core\src\iTextSharp.LGPLv2.Core\iTextSharp\text\pdf\PdfReader.cs:line 3097
   at iTextSharp.text.pdf.PdfReader.ReadPdfPartial() in D:\a\iTextSharp.LGPLv2.Core\iTextSharp.LGPLv2.Core\src\iTextSharp.LGPLv2.Core\iTextSharp\text\pdf\PdfReader.cs:line 3224
```

**Comment by VahidN** [comment]
Can you attach a sample file.

**Comment by 36PopTarts** [comment]
Sure. Here's the document after it was converted by LibreOffice. It opens fine in any PDF viewer like Adobe. Please ignore my lame sense of humor regarding the text of the document.
[test-qa.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/15336244/test-qa.pdf)

**Comment by 36PopTarts** [comment]
Thanks for updating. This is fixed now in my application
