### ISSUE TITLE
How to get text content from PDF

### ISSUE THREAD

**Issue by AndrePScope** [VahidN/iTextSharp.LGPLv2.Core#15]
Is it possible to parse PDF for getting Text content via iTextSharp.LGPLv2.Core?

**Comment by AndrePScope** [comment]
Sorry, I think, my question is duplicate of issue #7

**Comment by VitaliyMF** [comment]
as alternative you can try another approach for getting text content from PDF: use poppler command line tools (pdftotext or pdftohtml).
