### ISSUE TITLE
Compatibility of PdfStamper

### ISSUE THREAD

**Issue by circler3** [VahidN/iTextSharp.LGPLv2.Core#16]
# Summary of the issue
When I tried to modify acrofields of a non-English pdf. I found that I cannot save the pdf file. It stuck at the `PdfStamperImp.cs` Line 892. The program stopped but did not throw any exception. The pdf was created from a *Microsoft Word* document by *Phantom PDF*.

Then I tried a different version of PDF, PDFs directly produced by *Microsoft Word* are normal. The `altMetadata` seemed to be different in *Phantom PDF*.

## Environment

```
The in-use version:Latest version source and binary 1.3.2
Operating system: 
OS: WIN10
IDE:  Visual Studio 2017 Community 15.4
```

## Example code/Steps to reproduce:

```
1. Find a PDF produced by Phantom PDF
2. Open it and call PdfStamper.Close()
```

## Output:

```
Exception message:N/A
Full Stack trace:N/A
```

**Comment by VahidN** [comment]
Can you attach a sample file?

**Comment by circler3** [comment]
[123.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/1491478/123.pdf)
this is a sample file.

**Comment by VahidN** [comment]
Sorry. I can't reproduce your issue. First I added [a new test](https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/0b348fb0c1d1d0196c053c7895883bfed062e50c) based on your attached file. And here is its produced result: [Verify_Issue16_CanBe_Processed.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/1491921/Verify_Issue16_CanBe_Processed.pdf)
