### ISSUE TITLE
Problem in Image

### ISSUE THREAD

**Issue by akhiljain05** [VahidN/iTextSharp.LGPLv2.Core#17]
HI I am using this in my mvc core 2.0 application but image is not shown in pdf. Image code shown Below:-

 ```
 var logoImage = iTextSharp.text.Image.GetInstance("LogoImagepath");
                var logoImgCell = new PdfPCell
                {
                    Colspan = 2,
                    Border = 0,
                    HorizontalAlignment = Element.ALIGN_RIGHT
                };
                logoImage.WidthPercentage = 60;
                logoImage.Alignment = Element.ALIGN_RIGHT;
                logoImgCell.AddElement(logoImage);
                outerTable.AddCell(logoImgCell);
```

Please help

**Comment by VahidN** [comment]
Sorry. I can't reproduce your issue. First I added [a new test](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/Issues/Issue17.cs#L26) based on your data. After running it using the following command:
```
dotnet test --filter FullyQualifiedName~Verify_Issue17_CanBe_Processed
```
This is its produced result: [Verify_Issue17_CanBe_Processed.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/1499731/Verify_Issue17_CanBe_Processed.pdf)

**Comment by longinos10** [comment]
I am having the same issue it does not load images, I guess there will not be  fix

**Comment by VahidN** [comment]
This will help you everywhere:  [Writing the perfect question ](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
