### ISSUE TITLE
PdfContentByte.ShowTextAligned rotation is ignored

### ISSUE THREAD

**Issue by EvK** [VahidN/iTextSharp.LGPLv2.Core#21]
There is a bug in `PdfContentByte.showTextAligned` method. It goes like this:

    if (rotation.ApproxNotEqual(0)) {
        // branch which assumes rotation is 0    
    }
    else {
        // branch which assumes rotation is not 0
    }

So rotation is effictively ignored, because branches are switched. Changing that to

    if (rotation.ApproxEquals(0)) {

    } else {
  
    }

fixes the issue.

**Comment by VahidN** [comment]
Thanks for the report. It's fixed via https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/adb246769a9f27377834f36091fc5a64755ff270.
```
 dotnet add package iTextSharp.LGPLv2.Core --version 1.4.1 
```
