### ISSUE TITLE
PdfPTable is throwing an Error when creating new page

### ISSUE THREAD

**Issue by NeilWBruce** [VahidN/iTextSharp.LGPLv2.Core#22]
# Summary of the issue
When creating a new page which clones rows from the previous page I'm getting an exception from the RowSpanAbove in PdfPTable class.  

## Example code/Steps to reproduce:
From the looks of things this is because my header rows which I'm duplicating are using merging which causes the code to get confused.  I had look in the PdfPTable class and there this line of code (Line: 1361) which checks the aboveCell isn't null and then get's the next cell.  

```
  if (aboveCell == null)
            {
                int col = currCol - 1;
                aboveCell = aboveRow.GetCells()[col];
                while ((aboveCell == null) && (row > 0))
                    aboveCell = aboveRow.GetCells()[--col];
                return aboveCell != null && aboveCell.Rowspan > distance;
            }
```
This should work but clearly the while statement is checking the row hasn't gone below 0 not the column.  Simple fix this while statement should be (col > 0) not row

```
  if (aboveCell == null)
            {
                int col = currCol - 1;
                aboveCell = aboveRow.GetCells()[col];
                while ((aboveCell == null) && (col > 0))
                    aboveCell = aboveRow.GetCells()[--col];
                return aboveCell != null && aboveCell.Rowspan > distance;
            }
```

**Comment by VahidN** [comment]
Thanks for the report. Fixed via #https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/2a028bd0e22b668541d38706dbc5ea21733f73bc
