### ISSUE TITLE
Retaining original Html Style

### ISSUE THREAD

**Issue by rajagopal4890** [VahidN/iTextSharp.LGPLv2.Core#24]
# Summary of the issue
How do I retain the original style of the HTML with HtmlWorker?

## Environment
.net core 2.0
```
The in-use version: 1.4.2
Operating system:  Windows 10
IDE: VS 2017
```
## Example code/Steps to reproduce:
```csharp
string GridHtml = '<b>This is a test</b>
                     <br/>
                     <span style='color:blue;font-size:20pt;font-family:tahoma;font-style:italic;font-weight:bold'>
                        <b>Hi<b/>
                    </span>'

TextReader sr = new StringReader(GridHtml);
                Document pdfDoc = new Document(PageSize.A3, 10f, 10f, 100f, 0f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                HtmlWorker worker = new HtmlWorker(pdfDoc);
                var styles = new StyleSheet();
                var parsedHtml = HtmlWorker.ParseToList(sr, styles);
                pdfDoc.Open();
                foreach (IElement element in parsedHtml)
                {
                    pdfDoc.Add(element);
                }
                worker.Close();
                pdfDoc.Close();
                stream.Dispose();
```

## Output:
Original styles not applied like font and color.

**Comment by VahidN** [comment]
Try [this sample](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/Issues/Issue24.cs#L12) with this output:

![issue24](https://user-images.githubusercontent.com/766010/36071093-2ab7f476-0f1e-11e8-9aba-e36bed2b60f9.png)

**Comment by rajagopal4890** [comment]
Thanks for the response. Am passing this html from my mvc view via jquery and I find it weird that my styles are not reflecting. I'll take a look again and close this myself by today. Thanks again.
