### ISSUE TITLE
System.Drawing.Common dependency problem

### ISSUE THREAD

**Issue by mojtabakaviani** [VahidN/iTextSharp.LGPLv2.Core#25]
An assembly specified in the application dependencies manifest (*.deps.json) was not found:
    package: 'System.Drawing.Common', version: '4.5.0-preview1-25914-04'
    path: 'lib/netcoreapp2.0/System.Drawing.Common.dll'

must removing System.Drawing.Common from *.deps.json then solved.

**Comment by VahidN** [comment]
That package is still here
https://www.nuget.org/packages/System.Drawing.Common/

**Comment by VahidN** [comment]
Try using the .NET Core CLI instead:
```
dotnet add package iTextSharp.LGPLv2.Core
```
![dotnet_add](https://user-images.githubusercontent.com/766010/39968981-d84d8fc4-56ea-11e8-8908-79702423348f.png)

**Comment by mojtabakaviani** [comment]
Yes, but when deploy website on host this error raised.

**Comment by VahidN** [comment]
That error means your dotnet SDK version is behind the Microsoft.AspNetCore.All packages version. Making the versions match (either by reverting the package or upgrading the host SDK) will fix the problem.
