### ISSUE TITLE
Qr-code

### ISSUE THREAD

**Issue by AhmedSafaa95** [VahidN/iTextSharp.LGPLv2.Core#26]
# Summary of the issue

I need  to    print qr-code

## Environment
 Windows - linux 
```
The in-use version:
Operating system: 
IDE: (e.g. Visual Studio 2017)
```

**Comment by VahidN** [comment]
QRCode is not part of the current version. You can find it here in the latest version of iTextSharp
https://github.com/itext/itextsharp/blob/develop/src/core/iTextSharp/text/pdf/qrcode/
But the good news is it's licensed under "the Apache License, Version 2.0", which means it can be used with library which has an LGPL license. The Apache License does not place any restrictions on software that links to a plug-in or library that is distributed under the Apache license.

**Comment by VahidN** [comment]
Follow this sample:
https://github.com/VahidN/iTextSharp.LGPLv2.Core/tree/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/QRCode.Apache.License
