### ISSUE TITLE
Strong name missing warning

### ISSUE THREAD

**Issue by rimuln** [VahidN/iTextSharp.LGPLv2.Core#29]
# Summary of the issue

When used in VS2017 and Nuget after rebuild it warn:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8002	Referenced assembly 'iTextSharp.LGPLv2.Core, Version=1.4.4.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.	Sestavy	D:\Pracovni\git-repos\Lezeni-Core\Sestavy\CSC	1	Active

It is possible build it with strong name. We want replace are locally referenced downloade original dll with nuget version and in future switch to .netstandard and core.

Thanks for answer and migration of this LGPL version.

**Comment by VahidN** [comment]
A lot of people are against signing assemblies and me too!
- [FubuMVC Lessons Learned — Strong Naming Woes and Workarounds](https://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/)
- [Still Strong-Naming your Assemblies?](https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/)
- [Anything wrong with NOT signing a .NET assembly?](https://stackoverflow.com/questions/1197133/anything-wrong-with-not-signing-a-net-assembly)
- [Strong Name Bypass](https://blogs.msdn.microsoft.com/shawnfa/2008/05/14/strong-name-bypass/)
