### ISSUE TITLE
How to use Chinese code with iTextAsian.dll without ttf file

### ISSUE THREAD

**Issue by Immanuel-Licht** [VahidN/iTextSharp.LGPLv2.Core#30]
I need to create a Chinese PDF file,so I use the iTextAsian.dll and my code like this:

BaseFont.AddToResourceSearch(@"app\iTextAsian.dll");
BaseFont.AddToResourceSearch(@"app\iTextAsianCmaps.dll");
BaseFont songFont = BaseFont.CreateFont("STSong-Light", "UniGB-UCS2-H",BaseFont.NOT_EMBEDDED);

But it throws an error:Font STSong-Light with UniGB-UCS2-H is not recognized.
Could you tell me what should I do?Thanks.

**Comment by Immanuel-Licht** [comment]
Oh，I know  the problem.You change the RESOURCE_PATH.

iTextSharp.LGPLv2.Core=>public const string RESOURCE_PATH = "iTextSharp.LGPLv2.Core.iTextSharp.text.pdf.fonts.";
iTextSharp =>public const string RESOURCE_PATH = "iTextSharp.text.pdf.fonts.";

And the path of the font in iTextAsian.dll is still "iTextSharp.text.pdf.fonts."

**Comment by VahidN** [comment]
Are those dll's licenced under `LGPL`? No. So you didn't get the purpose of this library.

**Comment by VahidN** [comment]
Fixed here https://github.com/VahidN/iTextSharp.LGPLv2.Core/issues/34#issuecomment-470824602
