### ISSUE TITLE
Convert PDF file to image file

### ISSUE THREAD

**Issue by mrduyu** [VahidN/iTextSharp.LGPLv2.Core#31]
Hi,
I have multipage PDF files. I try to read page by page and get each page data as byte array to save as jpeg files. However, I couldn't find out why I am getting Parameter is not valid exception.
Here is my sample code.
Could you please about my issue? How can I save my each page of pdf as a jpg file.
**Note:** My test pdf file contains only images.
Thanks!
Emre.
![image](https://user-images.githubusercontent.com/40163745/50226904-82353600-03b5-11e9-8df4-29e897b644da.png)

**Comment by VahidN** [comment]
You can't! iTextSharp is not a PDF renderer and if you want to know what's in those bytes, try to open your PDF file with [iText Rups app](https://github.com/itext/rups/releases). It will show you the low level structure of a PDF file.

**Comment by VahidN** [comment]
[Here is an old sample](https://github.com/VahidN/PdfReport/blob/master/Samples/PdfThumbnailComparer/PdfThumbnailComparer.Lib/PdfToImage.cs) about converting a PDF file's pages to images. It uses the `Acrobat SDK` for that.
