### ISSUE TITLE
How to add custom css file

### ISSUE THREAD

**Issue by bymeftun** [VahidN/iTextSharp.LGPLv2.Core#32]
# Summary of the issue

How to add css file

Thank you

## Environment

```
The in-use version:
Operating system: 
Ubuntu or windows

Visual Studio 2017
```

## Example code/Steps to reproduce:

```
paste your core code

 StringBuilder html = new StringBuilder();
            html.Append("<!doctype html>");
            html.Append("<html>");
            html.Append("<head>");
            html.Append("<meta http-equiv='content-type' content='text/html;charset=UTF-8'>");
            html.Append("<title>Freebird Airlines e-Bilet</title>");            
            html.Append($"<link href='file:///{basePath}\\css\\stylegib.css' rel='stylesheet' type='text/css'>");
            html.Append($"<link href='file:///{basePath}\\css\\reset.css' rel='stylesheet' type='text/css'>");
            html.Append("</head>");
            html.Append("<body>");
            html.Append("</body></html>");

            MemoryStream ms = new MemoryStream();
            TextReader txtReader = new StringReader(html.ToString());
            Document doc = new Document(PageSize.A4, 25, 25, 25, 25);
            doc.SetMargins(doc.LeftMargin, doc.RightMargin, 35, 0);
            PdfWriter pdfWriter = PdfWriter.GetInstance(doc, ms);
            doc.Open();

            HtmlWorker htmlWorker = new HtmlWorker(doc);
            htmlWorker.StartDocument();
            htmlWorker.Parse(txtReader);
            htmlWorker.EndDocument();
            htmlWorker.Close();
            doc.Close();

            var byteData = Convert.ToBase64String(ms.ToArray());


            doc.Close();

            ms.Dispose();

**Comment by VahidN** [comment]
`HtmlWorker` doesn't support loading CSS files.
You can define [StyleSheets this way](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/HtmlWorkerTests.cs#L68) or you can define [inline styles](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/HtmlWorkerTests.cs#L111).

**Comment by ismaelgasparin** [comment]
Hello

I have problem with table inline styles in td and thead. 
HtmlWorker.ParseToList not working with ou without styles in Stylesheet for tables.

Is there such a limitation?

**Comment by VahidN** [comment]
- `HtmlWorker` is a very elementary HTML parser. Here you can find [which styles](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core/iTextSharp/text/html/simpleparser/IncCell.cs#L97) are supported for a cell and how.
- If you want a world class HTML-Parser, try wrappers of `wkhtmltopdf` such as:
https://github.com/rdvojmoc/DinkToPdf
https://github.com/tuespetre/TuesPechkin
https://github.com/topics/wkhtmltopdf?l=c%23
