### ISSUE TITLE
CurrentPageHeight

### ISSUE THREAD

**Issue by mohitkumarbhardwaj** [VahidN/iTextSharp.LGPLv2.Core#33]
can you add this property in next version.
class name is iTextSharp.text.pdf.PdfWriter.
I am not able access CurrentHeight because it is protected
public float CurrentPageHeight { get { return Pdf.CurrentHeight; } }

**Comment by VahidN** [comment]
Added via #https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/923640102f8f6508bd4eeb7f8764bb6e1a28e33f
