### ISSUE TITLE
Documentation.

### ISSUE THREAD

**Issue by serjebulavsky** [VahidN/iTextSharp.LGPLv2.Core#35]
# Summary of the issue
Not really an issue, but more of a question. Is there any resources/documents, related to this particular version, so i could look up for some examples, etc ? 
Thanks.

**Comment by VahidN** [comment]
You can find more examples [here](https://github.com/VahidN/iTextSharp.LGPLv2.Core/tree/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples). These examples are based on [this book](https://www.manning.com/books/itext-in-action-second-edition).

**Comment by serjebulavsky** [comment]
@VahidN thanks!
