### ISSUE TITLE
The libgdiplus install guide has an error on centos.

### ISSUE THREAD

**Issue by yqszt** [VahidN/iTextSharp.LGPLv2.Core#36]
# Summary of the issue
i try to create link using "ln -s /usr/local/lib/libgdiplus.so gdiplus.dll", but when i running my app,
it throws an error.
"Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.DrawingCore.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'gdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgdiplus: cannot open shared object file: No such file or directory"
when i create a new link using "ln -s /usr/local/lib/libgdiplus.so libgdiplus.so" it's working fine.

## Environment

```
The in-use version:1.5.0
Operating system: centos 7
Dotnet Core: 2.1.403
```

**Comment by VahidN** [comment]
Thanks. Fixed it via #https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/0a6b437d2969326f32ab27846e4bc4d71a306b1d
