### ISSUE TITLE
Newlines being ignored

### ISSUE THREAD

**Issue by markmcgookin** [VahidN/iTextSharp.LGPLv2.Core#37]
# Summary of the issue

I cannot get text to manually break to a new line within "columnText.SetSimpleColumn" I have added a new chunk with just "\n" in it, I have manually stripped out "\n" from my text and added a Chunk.NewLine, it seems to be ignoring my \n and any attempt to break onto a new line. The break characters are not displayed however, so they are being stripped out or processed somehow. 

All my text is wrapping on top of itself as well. While it's unreadable, it might be 'breaking' but not moving down a line, however I can't find a way to fix it.

## Environment

```
The in-use version: v1.5.0
Operating system: macOS
IDE: Visual Studio Code
Language: C# / dotnet core 2.2
```

## Example code/Steps to reproduce:
NB: the unicode chars "\u00A0" are added to add a space before/after the text that doesn't get stripped out, but with/without this is makes no difference.

```
var ct = new ColumnText(cb);
var paragraph = new Paragraph();

var listofstrings = new List<string>();
listofstrings.Add("Some text that should \n break there \n and here");
foreach (var astring in listofstrings)
{
    var chunk = new Chunk($"\u00A0{astring}\u00A0", font);
    paragraph.Add(chunk);
}

ct.SetSimpleColumn(paragraph, ll_x, ll_y, ur_x, ur_y, 0, textElement.TextAlignment);
var status = ct.Go();
```

## Output:
![Screenshot 2019-05-09 at 16 35 27](https://user-images.githubusercontent.com/1053345/57467969-79b59d00-727b-11e9-8793-6f36e1e05279.png)

As you can see in the above picture, the text just wraps ontop of itself.

**Comment by VahidN** [comment]
[Try this](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/Issues/Issue37.cs#L28):
```csharp
var ct = new ColumnText(writer.DirectContent);

var text = new Phrase("TEST paragraph\nAfter Newline");
text.Add(new Chunk("\u00A0Test Test\u00A0"));
text.Add(new Chunk("\nNew line"));

ct.SetSimpleColumn(text, 34, 750, 580, 317, 15, Element.ALIGN_LEFT);
ct.Go();
```
With this output:
![issue37](https://user-images.githubusercontent.com/766010/57473895-260c7900-72a6-11e9-9532-7861cca54795.png)

**Comment by markmcgookin** [comment]
So I copied your code directly into my code and still having the same problem.
`
var text = new Phrase("TEST paragraph\nAfter Newline");
text.Add(new Chunk("\u00A0Test Test\u00A0"));
text.Add(new Chunk("\nNew line"));

ct.SetSimpleColumn(text, 34, 750, 580, 317, 15, Element.ALIGN_LEFT);
`

![Screenshot 2019-05-09 at 20 23 26](https://user-images.githubusercontent.com/1053345/57480691-5816de80-7298-11e9-8698-5402fe50b271.png)

You can see the text is 'breaking' but it's just all on one line.
