### ISSUE TITLE
Multiple fonts not working in Phrase

### ISSUE THREAD

**Issue by markmcgookin** [VahidN/iTextSharp.LGPLv2.Core#38]
# Summary of the issue
I have added multiple TTF fonts to font factory. When adding a phrase I have two blocks of text in two separate chunks added to the phrase, each of these chunks has a different font (retrieved from the font factory) when rendering the text all looks exactly the same.

## Environment

```
The in-use version: v1.5.0
Operating system: macOS
IDE: Visual Studio Code
Language: C# / dotnet core 2.2
```

## Example code/Steps to reproduce:
Apologies for some of the method calls here, but this is what I am using to detect a change in font (between runs) and if it is different alter it. 

I can see that the new font is being successfully retrieved from the font factory, and I can see it being correctly added to the chunk. I have checked the font files and the fonts are noticeably different to look at (one being a lot thinner) but when it is rendered it is all the same (with what appears to be the original font)

```
FontFactory.Register("Fonts/TTF/Swis721-BT.ttf", "SWIS721-BT");
FontFactory.Register("Fonts/TTF/Swis721-Thin-BT.ttf", "SWIS721-THIN-BT");

...

foreach (var run in textElement.Runs)
{
    var runFont = originalFontFromFactory;
    if(run.FontFamily != textElement.FontFamily && !String.IsNullOrEmpty(run.FontFamily))
    {
        runFont = FontFactory.GetFont(FontNameConvertor.GetAliasForMapItemFont(run.FontFamily), textElement.FontSize + (adjustment.IncreaseFont + increaseFont))
    }
    var chunk = new Chunk($"\u00A0{run.Text}\u00A0", runFont);
    phrase.Add(chunk);
}
```

## Output:

Actual Result
![Screenshot 2019-05-10 at 11 49 37](https://user-images.githubusercontent.com/1053345/57522100-bcc64d80-7319-11e9-836e-3004fb98fb6b.png)

Expected Result
![Screenshot 2019-05-10 at 11 50 22](https://user-images.githubusercontent.com/1053345/57522148-d49dd180-7319-11e9-90cf-6e26c8a590b0.png)

**Comment by VahidN** [comment]
I added a new test for this issue. You can [find it here](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/Issues/Issue38.cs#L26) with this output:
![issue38](https://user-images.githubusercontent.com/766010/57537814-4c8ceb80-735c-11e9-96f1-accfe38398bc.png)
 It uses this [GetUnicodeFont](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/TestUtils.cs#L88) method which has a correct encoding and also these types of fonts should be embedded.

**Comment by markmcgookin** [comment]
Thank you, using the "BaseFont.IDENTITY_H, BaseFont.EMBEDDED" arguments has sorted this

![Screenshot 2019-05-10 at 19 46 07](https://user-images.githubusercontent.com/1053345/57549768-5878ad80-735c-11e9-99d6-89e53fdcdaad.png)
