### ISSUE TITLE
Attempted to read past the end of the stream.

### ISSUE THREAD

**Issue by rh1314** [VahidN/iTextSharp.LGPLv2.Core#39]
[xxx.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/3371120/xxx.pdf)
   at iTextSharp.text.pdf.RandomAccessFileOrArray.ReadFully(Byte[] b, Int32 off, Int32 len) in \src\iTextSharp.LGPLv2.Core\iTextSharp\text\pdf\RandomAccessFileOrArray.cs:line 360

**Comment by VahidN** [comment]
How can I reproduce it? Where is your code?

**Comment by rh1314** [comment]
hi,code is shown below。pdf use `xxx.pdf`
    /// <summary>
    /// setWatermark
    /// </summary>
    /// <param name="inputfilepath"></param>
    /// <param name="outputfilepath"></param>
    /// <param name="waterMarkName"></param>
    /// <param name="permission"></param>
    public static void setWatermark(string inputfilepath, string outputfilepath, string waterMarkName)
        {
            PdfReader pdfReader = null;
            PdfStamper pdfStamper = null;
            try
            {
                pdfReader = new PdfReader(inputfilepath);
                pdfStamper = new PdfStamper(pdfReader, new FileStream(outputfilepath, FileMode.Create));
                int total = pdfReader.NumberOfPages + 1;
                iTextSharp.text.Rectangle psize = pdfReader.GetPageSize(1);
                float width = psize.Width;
                float height = psize.Height;
                PdfContentByte content;
                BaseFont font = BaseFont.CreateFont(@"C:\WINDOWS\Fonts\SIMFANG.TTF", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                PdfGState gs = new PdfGState();
                for (int i = 1; i < total; i++)
                {
                    content = pdfStamper.GetOverContent(i);                    
                    gs.FillOpacity = 0.3f;
                    content.SetGState(gs);
                    content.BeginText();
                    content.SetColorFill(BaseColor.LightGray);
                    content.SetFontAndSize(font, 100);
                    content.SetTextMatrix(0, 0);
                    content.ShowTextAligned(Element.ALIGN_CENTER, waterMarkName, width / 2 - 50, height / 2 - 50, 55);
                    content.EndText();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (pdfStamper != null)
                    pdfStamper.Close();
                if (pdfReader != null)
                    pdfReader.Close();
            }
        }

**Comment by rh1314** [comment]
pdfStamper.Close();------ This leads to failure.

**Comment by VahidN** [comment]
I added [a new test based on your code](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/Issues/Issue39.cs#L15), and I can't reproduce your issue. It works:
![issue39](https://user-images.githubusercontent.com/766010/60867045-23df8000-a23f-11e9-9d6d-3e136d31c7d2.png)

Make sure you are using `Version 1.5.0`
```
Install-Package iTextSharp.LGPLv2.Core -Version 1.5.0
```

**Comment by rh1314** [comment]
[test.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/3372019/test.pdf)
sorry,try this。

**Comment by rh1314** [comment]
I use this too.
<PackageReference Include="iTextSharp.LGPLv2.Core" Version="1.5.0" />

**Comment by VahidN** [comment]
About your `test.pdf`. That file is a corrupted file and can't be opened with Adobe Reader:
![issue39_@](https://user-images.githubusercontent.com/766010/60874770-c999eb80-a24d-11e9-94f0-a8ce9bdd0475.png)

**Comment by rh1314** [comment]
It can be previewed in browser。And there will be a lot of such documents，Can we solve it?

**Comment by rh1314** [comment]
This file can be previewed in browser。There are many files of this type。Can we solve it?

**Comment by rh1314** [comment]
This file can be previewed in the browse。There are many files of this type。Can we solve it?

**Comment by rh1314** [comment]
It's normal to use this tool.
http://www.pdfdo.com/pdf-add-watermark.aspx

[example](http://q4.pdfdo.com/Download/070917241551.pdf?t=645)

**Comment by VahidN** [comment]
Fixed it via #https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/a2f225bdc54a339102d8637b8c64fc6cf85aff2a
