### ISSUE TITLE
PdfReader & PdfStamper doesn't support disposable!

### ISSUE THREAD

**Issue by pMonfared** [VahidN/iTextSharp.LGPLv2.Core#4]
![image](https://cloud.githubusercontent.com/assets/10448255/24940818/f85d96f6-1f5a-11e7-9ac4-9c40a3555585.png)

```
using (var pdfReader = new PdfReader(fileLocation))
                {

                }
```

**Comment by VahidN** [comment]
Yes. It's based on the iTextSharp 4.x, not 5.x and has a different design and license.
[Here is a sample about PdfReader & PdfStamper in this version](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/74d5439a42c1c4f2b599434f1c7d97bee93dffe4/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples/Chapter07Tests.cs#L12).
