### ISSUE TITLE
Importing SVG / EPS

### ISSUE THREAD

**Issue by HolyOne** [VahidN/iTextSharp.LGPLv2.Core#41]
Hello, is there a way to import vector graphics as vector in pdf file?

**Comment by VahidN** [comment]
It supports [wmf files](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core/iTextSharp/text/ImgWMF.cs). You can import them as a regular Image file.
