### ISSUE TITLE
Any support for fdfWriter.SetFieldAsImage() ?

### ISSUE THREAD

**Issue by RichardGrundy** [VahidN/iTextSharp.LGPLv2.Core#45]
# Summary of the issue
Previously in iTextSharp we were able to add images for image fields in FdfWriter like so:

```
//Add barcode image
Image img = Image.GetInstance(barcode_jpg);
fdfWriter.SetFieldAsImage("Barcode", img);
fdfWriter.Write();

```
Is there a way to do this with the .Net Core port that i am not seeing?
Thanks in advance.

## Environment

```
iTextSharp.LGPLv2.Core version: 
.NET Core SDK version: 
IDE: Rider
```

**Comment by VahidN** [comment]
Have you tried combination of [stamper.AcroFields](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/Issues/Issue34.cs#L51) and "[How can i set an image to a pdf field in existing pdf file?](https://stackoverflow.com/questions/8656844/how-can-i-set-an-image-to-a-pdf-field-in-existing-pdf-file)"
