### ISSUE TITLE
fonts in bold have less clarity

### ISSUE THREAD

**Issue by anjanaB23489** [VahidN/iTextSharp.LGPLv2.Core#46]
[12452.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/3982228/12452.pdf)
# Summary of the issue
when using fonts other than defaults,creating pdf have less clarity in case of bold letters on . It shows some shadow in letters.Sample file is attached above. 

## Environment

```
iTextSharp.LGPLv2.Core version: 1.6.1
.NET Core SDK version: 2.1.0
IDE: Visual studio 2019
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
It only depends on the design of the font. You should try other fonts.
