### ISSUE TITLE
how can port to .NetStandard?

### ISSUE THREAD

**Issue by pMonfared** [VahidN/iTextSharp.LGPLv2.Core#5]
Can? or Can't?
What's your Solution for use this project in .NetStandard?

**Comment by VahidN** [comment]
What do you want to do exactly?

**Comment by pMonfared** [comment]
don't Install in netstandard 1.6.1 in VS 2017 (.NetStandard Class Library)
but Install correctly in (.NetCore Class Library)

**Comment by VahidN** [comment]
That's because its default target framework version is **1.4**. change it to 1.6 and it will work as expected.
![nets](https://cloud.githubusercontent.com/assets/766010/25007026/302eb866-2074-11e7-83d2-8c92571f6a10.png)
