### ISSUE TITLE
I have a big html DOM with some links, While parsing I got "invalid uri the hostname could not be parsed."

### ISSUE THREAD

**Issue by kiranshahi** [VahidN/iTextSharp.LGPLv2.Core#50]
# Summary of the issue
I have a big html DOM with some links, While parsing I got `invalid uri the hostname could not be parsed.` 
![Screenshot (4)](https://user-images.githubusercontent.com/15968059/72869817-7a5d6900-3d0e-11ea-9593-1d535ad0c747.png)

## Environment

```
iTextSharp.LGPLv2.Core version: 
.NET Core SDK version: 2.2
IDE: Visual studio 2019
```

## Example code/Steps to reproduce:

```
MemoryStream stream = new MemoryStream();
var document = new Document();
var pdfWriter = PdfWriter.GetInstance(document, stream);
document.Open();
var objects = HtmlWorker.ParseToList(
    new StringReader(html),
    null
);
foreach(IElement element in objects) {
    document.Add(element);
};
pdfWriter.Close();
document.Close();
stream.Position = 0;
return stream;
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
It only cares about images. create your own [IImageProvider](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/591270bb05dd512a18de03a528ff24fb07b7a75e/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples/Chapter09Tests.cs#L101) and [use it](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/591270bb05dd512a18de03a528ff24fb07b7a75e/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples/Chapter09Tests.cs#L31).
