### ISSUE TITLE
NullReferenceException on copy link annotation to new document 

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [VahidN/iTextSharp.LGPLv2.Core#55]
i have pdf document which contains several link annotations: some of them is external link to web site, other is link inside document
i need to create copy of this document and add watermark on each page.

so, i create PageEventHandler and add corresponded object to document with no problem. But after i copied links from source documents to copy i have NullReferenceException
```

for (int page = 0; page < reader.NumberOfPages; page++)
{
    var links = reader.GetLinks(page + 1).ToArray();

   foreach (PdfAnnotation.PdfImportedLink link in links)
   {
	var annotation = link.CreateAnnotation(writer);
	writer.AddAnnotation(annotation);
    }
}

document.Close(); // <--NullReferenceException here
```
 
where writer is PdfWriter for document which contains full copy of source document

exception generated with following call stack:
```
iTextSharp.text.pdf.PdfWriter.GetNewObjectNumber(iTextSharp.text.pdf.PdfReader reader, int number, int generation)	 	
iTextSharp.text.pdf.PrIndirectReference.ToPdf(iTextSharp.text.pdf.PdfWriter writer, System.IO.Stream os)
iTextSharp.text.pdf.PdfArray.ToPdf(iTextSharp.text.pdf.PdfWriter writer, System.IO.Stream os)
iTextSharp.text.pdf.PdfDictionary.ToPdf(iTextSharp.text.pdf.PdfWriter writer, System.IO.Stream os)
iTextSharp.text.pdf.PdfIndirectObject.WriteTo(System.IO.Stream os)
iTextSharp.text.pdf.PdfWriter.PdfBody.Add(iTextSharp.text.pdf.PdfObject objecta, int refNumber, bool inObjStm)	
iTextSharp.text.pdf.intern.PdfAnnotationsImp.RotateAnnotations(iTextSharp.text.pdf.PdfWriter writer, iTextSharp.text.Rectangle pageSize)	
iTextSharp.text.pdf.PdfDocument.NewPage()
...
```

after searching by this problem i found only one thread on forum (http://itext.2136553.n4.nabble.com/Null-pointer-exception-in-PdfWriter-td2313742.html)  with suggested workaround. but i didn't find this patch in any forks of itestsharp, so i don't think that this is correct way.

## Environment
```
iTextSharp.LGPLv2.Core version:  1.6.5
.NET Core SDK version: 2.1
IDE: vs 2019
```

**Comment by VahidN** [comment]
Added it via#https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/e8e5637194cbec28d35918be1dcfeb2e6730d6b3

**Comment by anatoly-kryzhanovsky** [comment]
thanks for fast reaction and update
in 1.6.6 no exception was throwed, but link inside document not working...

**Comment by VahidN** [comment]
Sorry I can't help you. Because I don't know how to reproduce your problem, even I couldn't test it.

**Comment by anatoly-kryzhanovsky** [comment]
i could try to create minimum working example for this problem if it will help you

**Comment by anatoly-kryzhanovsky** [comment]
test

**Comment by anatoly-kryzhanovsky** [comment]
```
using (var sourceStream = File.Open("input.pdf", FileMode.Open))
{
	using (var documentStream = File.Create("output.pdf"))
	{
		var document = new Document();
		var writer = PdfWriter.GetInstance(document, documentStream);
		writer.PageEmpty = false;

		var reader = new PdfReader(sourceStream);
		reader.ConsolidateNamedDestinations();
		PdfContentByte contentByte = null;

		writer.Outlines = SimpleBookmark.GetBookmark(reader);

		for (int page = 0; page < reader.NumberOfPages; page++)
		{
			document.SetPageSize(reader.GetPageSizeWithRotation(page + 1));

			if (page > 0)
				document.NewPage();
			else
			{
				document.Open();
				contentByte = writer.DirectContent;
			}
					
			var pageData = writer.GetImportedPage(reader, page + 1);
			contentByte.AddTemplate(pageData, 1, 0, 0, 1, 0, 0);

			var links = reader.GetLinks(page + 1);
			foreach (PdfAnnotation.PdfImportedLink link in links)
			{
				var annotation = link.CreateAnnotation(writer);
				writer.AddAnnotation(annotation);
			}
		}

		document.Close();
		documentStream.Seek(0, SeekOrigin.Begin);
	}
}
```
put attached pdf in same folder and execute this code. it will produce output.pdf wich contains copy of input.pdf, but all links not works (it still hoverable, but not redirect will performed then user click on it). in input.pdf all links works fine

[input.pdf](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/4492068/input.pdf)

**Comment by anatoly-kryzhanovsky** [comment]
ok... i think that you could ignore my question -i rewrite my code with pdfstamper and all work fine
