### ISSUE TITLE
can't display Chinese characters 

### ISSUE THREAD

**Issue by xw-fighting** [VahidN/iTextSharp.LGPLv2.Core#6]
I'm a chinese people ,I am very grateful to you wrote so good a tool.  In you under the help of this tool I can convert word files to PDF . but  I met a difficulty when I use you tool to add some chinese character to the pdf file which I want to creat . in the created  pdf file  it can not display the chinese character ,because I  am  a entry-level programmer  .it is too difficult to me ,so I'd like you to help me with my how to solve this problem.   I will be very grateful to you.

**Comment by VahidN** [comment]
I added a new sample to show how to create Chinese PDF files.

![china](https://cloud.githubusercontent.com/assets/766010/25080934/7e1bd9ba-235c-11e7-95d1-e92568b4595d.png)


- [More info](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples/Chapter11Tests.cs#L140)
- [Required font](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples/resources/fonts/SimSun.ttf)
- [How to create a Unicode font correctly](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/TestUtils.cs#L73)

**Comment by xw-fighting** [comment]
thinks a lot .
