### ISSUE TITLE
KhmerUnicode Script is not rendering correctly

### ISSUE THREAD

**Issue by chhinsras** [VahidN/iTextSharp.LGPLv2.Core#62]
this is my repo.
https://github.com/chhinsras/AspNetiTextSharp/tree/master

![Screen Shot 2020-10-09 at 3 03 28 PM](https://user-images.githubusercontent.com/31751665/95558550-993c9080-0a40-11eb-847f-a0398347302f.png)

**Comment by VahidN** [comment]
This is your answer https://github.com/VahidN/iTextSharp.LGPLv2.Core/issues/61#issuecomment-706025044
