### ISSUE TITLE
iTextSharp.LGPLv2.Core License 

### ISSUE THREAD

**Issue by VishalD10** [VahidN/iTextSharp.LGPLv2.Core#64]
I want to use this library in one my project which is used for commercial purpose ,I just wanted to know whether it is paid or free.

## Environment

```
iTextSharp.LGPLv2.Core version: 1.6.7
.NET Core SDK version: 3.1
IDE: Visual Studio 2019
```

**Comment by VahidN** [comment]
Read the readme file.
