### ISSUE TITLE
cp862 for hebrew

### ISSUE THREAD

**Issue by guymalka** [VahidN/iTextSharp.LGPLv2.Core#68]
# Summary of the issue
i try to use this with Hebrew  text and fail 
i dont find cp862 for Hebrew , if i use  28598 the program fails

## Environment
windows 10
```
iTextSharp.LGPLv2.Core version: 1.7
.NET Core SDK version: 3.1
IDE: vs2019
```

## Example code/Steps to reproduce:

var stream = new FileStream(@"D:\Test9.Pdf", FileMode.Create);
            var document = new Document(PageSize.A4);
            
            PdfWriter.GetInstance(document, stream);
            document.Open();
            BaseFont bf = BaseFont.CreateFont(BaseFont.TIMES_ROMAN, "Cp862", BaseFont.EMBEDDED);
            document.Add(new Paragraph(
                    $" : עם אנקודינג:"
                ));
            document.Close();
            stream.Dispose();
```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
For `Hebrew` you should use `Identity-H` + RTL tips.
- [How to show an RTL text correctly](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples/Chapter11Tests.cs#L155)
- [HTML to PDF sample for an RTL text ](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/HtmlWorkerTests.cs#L112)

**Comment by guymalka** [comment]
here is the code, very similar to the code in the example you sent
i get empty rectangle  


`var pdfDoc = new Document(PageSize.A4);
            var fileStream = new FileStream(@"D:\Test90.Pdf", FileMode.Create);
            PdfWriter.GetInstance(pdfDoc, fileStream);
            pdfDoc.Open();
            var table = new PdfPTable(numColumns: 1)
            {
                RunDirection = PdfWriter.RUN_DIRECTION_RTL,
                ExtendLastRow = true
            };

            var pdfCell = new PdfPCell(new Phrase("טקסט בעברית", new Font(0, 10)))
            {
                RunDirection = PdfWriter.RUN_DIRECTION_RTL
            };
            table.AddCell(pdfCell);
            pdfDoc.Add(table);

            pdfDoc.Close();
            fileStream.Dispose();`

**Comment by VahidN** [comment]
Change the `new Font(0, 10)` to 
```C#
var tahomaFont = TestUtils.GetUnicodeFont("Tahoma", TestUtils.GetTahomaFontPath(), 10, Font.NORMAL, BaseColor.Black);
```
And [this is how](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/TestUtils.cs#L88) you should create and cache a Unicode font.

**Comment by guymalka** [comment]
the only way is to write "tahoma" font and use the tiff file ?

**Comment by VahidN** [comment]
Yes. This how `BaseFont.IDENTITY_H` encoding works.

**Comment by guymalka** [comment]
thanks , worked
