### ISSUE TITLE
Is UnethicalReading supported?

### ISSUE THREAD

**Issue by brooklynDev** [VahidN/iTextSharp.LGPLv2.Core#69]
Other versions of iTextSharp have a property or a function to turn on "Unethical Reading" which enables open PDFs with certain encryption types. In this (awesome) library, I haven't found a way to do that. Is there some other setting that I can turn on that will provide the same functionality? Thanks in advance!

**Comment by VahidN** [comment]
Yes. It's call [PdfReader.AllowOpenWithFullPermissions](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/13edb68d4169d050d4290360cef31c89189831ff/src/iTextSharp.LGPLv2.Core/iTextSharp/text/pdf/PdfReader.cs#L133).
