### ISSUE TITLE
SimpleTextExtractionStrategy ?

### ISSUE THREAD

**Issue by jgrossrieder** [VahidN/iTextSharp.LGPLv2.Core#7]
Hi,

I was trying to use your project for my .NetCore app, to replace the usage of the .net 4.0 lib which I can't use.

I managed to create the PdfReader, but I can't find what would be the equivalent of PdfTextExtractor class, do you have any idea?

**Comment by VahidN** [comment]
PdfTextExtractor exists in v5.0.2+ with AGPL license.

**Comment by jgrossrieder** [comment]
Just for my understanding: you only port the V2 and therefore I will not be able to parse the text in PDF ? 
Or is there another way with the V2?

**Comment by VahidN** [comment]
- This version doesn't contain the whole `iTextSharp.text.pdf.parser` namespace which is present in the v5.0.2+.
- But this version has the infrastructure of the `iTextSharp.text.pdf.parser` namespace, such as [Test_Extract_Text method](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/PdfReaderTests.cs#L61).

**Comment by jgrossrieder** [comment]
@VahidN I tried to use it, but the results is just word in an incorrect direction, there is no way I can use the result :(

**Comment by AndrePScope** [comment]
Hello @VahidN !
I use your sample Test_Extract_Text method for getting words and creation full text index after that. This method works good for me, but not for all pdf-s. Some extractions return waste. I expect that it can be problem with encoding or something like it... Could you suggest me something?

**Comment by VahidN** [comment]
I added a new sample to demonstrate how different PDF writers, create a PDF file:
[Test_Draw_Text()](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/PdfReaderTests.cs#L110)
If you run it, you will see this output:
![pdftext](https://user-images.githubusercontent.com/766010/32687513-230abba2-c6d3-11e7-854c-02c3a74b8392.png)
Which is equal to this output in PDF language:
```
q
BT
36 806 Td
0 -18 Td
/F1 12 Tf
(Test)Tj
0 0 Td
ET
Q
BT
/F1 12 Tf
88.66 367 Td
(ld)Tj
-22 0 Td
(Wor)Tj
-15.33 0 Td
(llo)Tj
-15.33 0 Td
(He)Tj
ET
q 1 0 0 1 36 343 cm /Xf1 Do Q
```
Or
```
SaveGraphicsState(); // q
BeginText(); // BT
MoveTextPos(36, 806); // Td
MoveTextPos(0, -18); // Td
SelectFontAndSize("/F1", 12); // Tf
ShowText("(Test)"); // Tj
MoveTextPos(0, 0); // Td
EndTextObject(); // ET
RestoreGraphicsState(); // Q
BeginText(); // BT
SelectFontAndSize("/F1", 12); // Tf
MoveTextPos(88.66, 367); // Td
ShowText("(ld)"); // Tj
MoveTextPos(-22, 0); // Td
ShowText("(Wor)"); // Tj
MoveTextPos(-15.33, 0); // Td
ShowText("(llo)"); // Tj
MoveTextPos(-15.33, 0); // Td
ShowText("(He)"); // Tj
EndTextObject(); // ET
SaveGraphicsState(); // q
TransMatrix(1, 0, 0, 1, 36, 343); // cm
XObject("/Xf1"); // Do
RestoreGraphicsState(); // Q
```
As you can see, PDF object is essentially a canvas and we can draw texts on it. In this case, your best choice to convert this output to a its textual form is using an **OCR**.

**Comment by VitaliyMF** [comment]
@AndrePScope for indexing purposes you can check another approach that might give better results; instead of iTextSharp try pdftotext command line utility (part of [poppler tools](https://poppler.freedesktop.org/), it has both windows and linux builds).
