### ISSUE TITLE
PdfReader not opened with owner password

### ISSUE THREAD

**Issue by devfadl** [VahidN/iTextSharp.LGPLv2.Core#75]
# Summary of the issue
when try to open an encrypted pdf file

## Environment

```
iTextSharp.LGPLv2.Core version: 1.7
.NET Core SDK version: 5.0.2
IDE: VS 2019
```

## Example code/Steps to reproduce:

```
var pdfRdr = new PdfReader(sourcePdf);
```

## Output:
exception with error 

```
Exception message: PdfReader not opened with owner password
Full Stack trace:
```

**Comment by VahidN** [comment]
[Follow this sample.](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/fc741e6114fbb74778241c88f581b7c0f0f867e5/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples/Chapter12Tests.cs#L60)
