### ISSUE TITLE
Document in use until .net process is ended

### ISSUE THREAD

**Issue by jboone0052** [VahidN/iTextSharp.LGPLv2.Core#8]
I'm having an issue where when I create a document in a .net core web app. The pdf is created, but when I try to view it is says that the document is in use by another process. I have to stop my web app in order to see the created pdf. I've been using itextsharp for years and in my old version I didn't have this issue. 
Below is some code i'm using to create the pdf. 
 ```
var document = new Document();
PdfWriter.GetInstance(document, new FileStream(path + "\\" + lastName + ", " + firstName + " " + todaysDate + ".pdf", FileMode.Create));
 document.Open();
```

Do some work on document (code omitted for brevity)

`document.Close();`

**Comment by VahidN** [comment]
You are not disposing the `FileStream` and it won't be closed and disposed automatically at the end. 
[Here you can find more samples](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples/Chapter11Tests.cs#L134) about how to use it and how to dispose resources.

**Comment by jboone0052** [comment]
Thank you that did it. I was just copying the code from my previous version assuming it should all work the same. Well you know what they say about assuming. 

Thanks for your help. And thanks for porting this over for everyone to use.
