### ISSUE TITLE
Consider dropping support for netstandard1.3

### ISSUE THREAD

**Issue by ViktorHofer** [VahidN/iTextSharp.LGPLv2.Core#87]
# Summary of the issue
Most libraries already target .NET Standard 2.0 or a supported platform that support .NET Standard 2.0 like
- .NET Core 2.0 and above
- .NET Framework 4.6.1 and above
- UAP10.0.16299

I would suggest to consider dropping support for .NET Standard 1.3 and older .NET Framework versions in favor of a broader API set a simplified dependency graph. Other open source repositories are dropping support for older targets as well, i.e. xunit v3. I would be willing to send a PR but wanted to open an issue to discuss this first.

**Comment by VahidN** [comment]
V 1.8.0 drops netstandard1.3.
