### ISSUE TITLE
Nuget install fails due to missing dependency

### ISSUE THREAD

**Issue by WrathZA** [VahidN/iTextSharp.LGPLv2.Core#9]
λ Install-Package iTextSharp.LGPLv2.Core

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'nuget.org'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
Install-Package : Unable to find dependent package(s) (CoreCompat.System.Drawing)
At line:1 char:1
+ Install-Package iTextSharp.LGPLv2.Core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CoreCompat.System.Drawing:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPac
   kage

**Comment by VahidN** [comment]
It's not missing. It's _still_ [here](https://www.nuget.org/packages/CoreCompat.System.Drawing/).
Try this command:
```
Install-Package iTextSharp.LGPLv2.Core -ProviderName NuGet -Source https://www.nuget.org/api/v2/ -Verbose
```

**Comment by WrathZA** [comment]
λ Install-Package iTextSharp.LGPLv2.Core -ProviderName NuGet -Source https://www.nuget.org/api/v2/ -Verbose
VERBOSE: Using the provider 'NuGet' for searching packages.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='iTextSharp.LGPLv2.Core'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'iTextSharp.LGPLv2.Core'.
VERBOSE: Performing the operation "Install Package" on target "Package 'iTextSharp.LGPLv2.Core' version '1.2.4' from
'nuget.org'.".

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'nuget.org'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='iTextSharp.LGPLv2.Core'' for ''.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='CoreCompat.System.Drawing'' for ''. Install-Package : Unable to find dependent package(s) (CoreCompat.System.Drawing)
At line:1 char:1
+ Install-Package iTextSharp.LGPLv2.Core -ProviderName NuGet -Source ht ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CoreCompat.System.Drawing:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPac
   kage

**Comment by WrathZA** [comment]
Also tried to install dependency directly. Very weird. 

Install-Package CoreCompat.System.Drawing -ProviderName NuGet -Source https://www.nuget.org/api/v2/ -Verbose
VERBOSE: Using the provider 'NuGet' for searching packages.
VERBOSE: Searching repository 'https://www.nuget.org/api/v2/FindPackagesById()?id='CoreCompat.System.Drawing'' for ''. VERBOSE: Total package yield:'0' for the specified package 'CoreCompat.System.Drawing'.
Install-Package : No match was found for the specified search criteria and package name 'CoreCompat.System.Drawing'.
Try Get-PackageSource to see all available registered package sources.
At line:1 char:1
+ Install-Package CoreCompat.System.Drawing -ProviderName NuGet -Source ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], E
   xception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by VahidN** [comment]
You should report it here: https://github.com/PowerShell/PowerShellGet/issues

**Comment by VahidN** [comment]
Reported here: https://github.com/PowerShell/PowerShellGet/issues/122

**Comment by VahidN** [comment]
[Try using dotnet CLI instead](http://ardalis.com/how-to-add-a-nuget-package-using-dotnet-add)
```
> dotnet add package iTextSharp.LGPLv2.Core
```
