### ISSUE TITLE
XFA form XML doesn't get properly set (it adds XML declaration element)

### ISSUE THREAD

**Issue by cearny** [VahidN/iTextSharp.LGPLv2.Core#95]
# Summary of the issue

I am trying to fill out a dynamic XFA form, and have been having trouble doing this with this library, compared to the other LGPL implementation over at https://github.com/schourode/iTextSharp-LGPL

I finally nailed it down to the way `XfaForm.SerializeDoc` is implemented here (using `XmlWriter.Create`) versus there (using `XmlTextWriter`).

See https://github.com/schourode/iTextSharp-LGPL/blob/master/src/core/iTextSharp/text/pdf/XfaForm.cs#L220 (there) versus https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core/iTextSharp/text/pdf/XfaForm.cs#L164 (here).

The trouble with the implementation here is that it adds an extra `<xml version...` tag at the beginning of the serialized element, which breaks PDF readers trying to parse it (as they probably expect just one element).

Would you be open to a PR that changes the code to something similar to the other project or at least makes it look similar to https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/fd887210f57395005df9554634527233d4acb200/src/iTextSharp.LGPLv2.Core/iTextSharp/text/xml/xmp/XmpReader.cs#L86 (basically by adding `OmitXmlDeclaration = true` like it is there already)

## Environment

```
iTextSharp.LGPLv2.Core version: 
.NET Core SDK version: 3.1
IDE: VS 2019
```

## Example code/Steps to reproduce:

```
// as explained above
```

## Output:

```
// error does not occur
```

**Comment by cearny** [comment]
I was able to very easily prepare a PR for this:

https://github.com/VahidN/iTextSharp.LGPLv2.Core/pull/96

 Please let me know if it requires any changes.

**Comment by VahidN** [comment]
Thank you.

**Comment by cearny** [comment]
@VahidN thanks for the very quick turnaround, but it seems I miscalculated the issue.

Let me explain, using some screenshots from iText RUPS.

Initially, the library used to behave like this, when replacing the XFA form:

![image](https://user-images.githubusercontent.com/1176043/127153617-e93f151a-ea76-4ff8-9492-f9f835e709e9.png)

The change above fixes this. *But that was actually not the full issue*. If you pay attention, you'll see that the first element is *not* `<xfa:datasets>` but instead its child `<xfa:data>` as the code is using `XmlNode.WriteContentTo`, which only writes the *InnerXml* content, so when serializing an element, the element itself does not get written to the output stream!

So, now the output is:

![image](https://user-images.githubusercontent.com/1176043/127154166-6fdbf29b-9071-432c-8df9-51eefb450ca7.png)

This is also incorrect.

The other library is using `XmlTextWriter` which is all and good, but is not available in .NET Standard 1.3 (not even as a NuGet) so it's a no-go to simply use the same, unless you are okay with a nasty breaking change.

Alternatively, `XmlSerializer` can be used, which only requires a new dependency in .NET Standard 1.3 (namely `System.Xml.XmlSerializer`). I changed the implementation to use that one and it seems to be working and compiling fine on all targets.

Now the output is the following:

![image](https://user-images.githubusercontent.com/1176043/127156400-2b0f8ea0-a231-435b-8039-6df3cdbf5c8f.png)

I have prepared a second PR for this, which also updates the test so now it looks to see that the element really is serialized in the output. You can find it at https://github.com/VahidN/iTextSharp.LGPLv2.Core/pull/97

By the way I found another usage for `XmlNode.WriteContentTo` in `XmpReader` at https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core/iTextSharp/text/xml/xmp/XmpReader.cs#L105 ; not sure if that one also causes a similar issue, but from a cursory glance, there is a difference to iTextSharp-LGPL's implementation (see: https://github.com/schourode/iTextSharp-LGPL/blob/master/src/core/iTextSharp/text/xml/xmp/XmpReader.cs#L153)

I apologize for missing the whole issue the first time around!
