### ISSUE TITLE
How to add signature sign by X509Certificate?

### ISSUE THREAD

**Issue by ngochoaitn** [VahidN/iTextSharp.LGPLv2.Core#98]
# Summary of the issue
In Net Framework i can use MakeSignature.SignDetached to sign pdf file, but in this library it not work.
How can sign a pdf file by X509Certificate?

## Environment

```
iTextSharp.LGPLv2.Core version: 1.7.3
.NET Core SDK version:  .NET5
IDE: Visual studio
```

## Example code/Steps to reproduce:

```
Don't know write code
```

**Comment by VahidN** [comment]
[I have a sample about it here](https://github.com/VahidN/PdfReport.Core/blob/c5f0d8b0725042c819f6c1a80417dce612a10f6c/src/PdfRpt.Core/Core/Security/SignatureWriter.cs#L33).
